import { afterEach, describe, expect, test } from "bun:test";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import {
  PLUGIN_BUILD_BUN_VERSION,
  assertPluginBuildBunVersion,
  assertPluginRuntimeArtifactsExact,
} from "../scripts/build-plugin-runtime";

const repoRoot = resolve(import.meta.dir, "..");
const generatorEntrypoint = resolve(repoRoot, "scripts/build-plugin-runtime.ts");
const committedDist = resolve(repoRoot, "plugins/claude-code/dist");
const pluginRuntimeArtifactPaths = ["semctx-mcp.js", "semctx-shared.js", "semctx.js"] as const;
const portableTypeScriptPrelude =
  'var __dirname=import.meta.dir+"/typescript-lib",__filename=__dirname+"/typescript.js";';
const temporary: string[] = [];
let builtArtifacts: Promise<Map<string, Uint8Array>> | undefined;

/**
 * Bun 1.3.13 fails the split runtime build when `Bun.build` runs inside the `bun test` process, and
 * the failed build then poisons the runner's module resolver for the remaining files. The generator
 * is therefore never called here: a child process runs the real entrypoint in `--check` mode, which
 * builds the expected artifacts in memory and asserts the committed bytes of both plugin dists equal
 * that build. Once it succeeds, the committed bytes *are* the generated bytes, so this test reads
 * them off disk.
 */
async function verifiedArtifacts(): Promise<Map<string, Uint8Array>> {
  const child = Bun.spawn([process.execPath, generatorEntrypoint, "--check"], {
    cwd: repoRoot,
    stdin: "ignore",
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
    child.exited,
  ]);
  if (exitCode !== 0) {
    throw new Error(
      `plugin artifact check subprocess exited with code ${exitCode}\nstdout:\n${stdout}\nstderr:\n${stderr}`,
    );
  }

  const built = new Map<string, Uint8Array>();
  for (const artifactPath of pluginRuntimeArtifactPaths) {
    built.set(artifactPath, new Uint8Array(readFileSync(resolve(committedDist, artifactPath))));
  }
  return built;
}

function artifacts(): Promise<Map<string, Uint8Array>> {
  builtArtifacts ??= verifiedArtifacts();
  return builtArtifacts;
}

function chunkPath(paths: string[]): string {
  const chunks = paths.filter((path) => path === "semctx-shared.js");
  expect(chunks).toHaveLength(1);
  return chunks[0]!;
}

function materialize(built: Map<string, Uint8Array>): string {
  const dist = mkdtempSync(join(tmpdir(), "semctx-plugin-artifacts-"));
  temporary.push(dist);
  for (const [relativePath, bytes] of built) {
    const output = resolve(dist, relativePath);
    mkdirSync(dirname(output), { recursive: true });
    writeFileSync(output, bytes);
  }
  return dist;
}

afterEach(() => {
  for (const path of temporary.splice(0)) {
    rmSync(path, { recursive: true, force: true });
  }
});

describe("split plugin runtime build", () => {
  test("emits both public entries and one shared chunk", async () => {
    const built = await artifacts();
    const paths = [...built.keys()].sort();

    expect(paths).toContain("semctx-mcp.js");
    expect(paths).toContain("semctx.js");
    expect(paths).toHaveLength(3);
    chunkPath(paths);
  }, 30_000);

  test("places the portable TypeScript payload only in the shared chunk", async () => {
    const built = await artifacts();
    const paths = [...built.keys()];
    const sharedChunk = chunkPath(paths);

    for (const [relativePath, bytes] of built) {
      const body = new TextDecoder().decode(bytes);
      expect(body).not.toContain(JSON.stringify(repoRoot).slice(1, -1));
      expect(body).not.toMatch(/typescript@[^"']+node_modules[^"']+typescript[^"']+lib/);
      expect(body.includes(portableTypeScriptPrelude)).toBe(relativePath === sharedChunk);
    }
  }, 30_000);

  test("diagnoses an unsupported Bun generator version", () => {
    expect(Bun.version).toBe(PLUGIN_BUILD_BUN_VERSION);
    expect(() => assertPluginBuildBunVersion("0.0.0-test")).toThrow(
      new RegExp(`requires Bun ${PLUGIN_BUILD_BUN_VERSION}`),
    );
  });
});

describe("exact plugin runtime artifact set", () => {
  test("accepts the complete generated set", async () => {
    const built = await artifacts();
    const dist = materialize(built);

    expect(() => assertPluginRuntimeArtifactsExact(dist, built)).not.toThrow();
  }, 30_000);

  test("rejects a missing shared chunk", async () => {
    const built = await artifacts();
    const dist = materialize(built);
    const sharedChunk = chunkPath([...built.keys()]);
    rmSync(resolve(dist, sharedChunk));

    expect(() => assertPluginRuntimeArtifactsExact(dist, built)).toThrow(/artifact set/);
  }, 30_000);

  test("rejects stale shared chunk bytes", async () => {
    const built = await artifacts();
    const dist = materialize(built);
    const sharedChunk = chunkPath([...built.keys()]);
    writeFileSync(resolve(dist, sharedChunk), "stale");

    expect(() => assertPluginRuntimeArtifactsExact(dist, built)).toThrow(/stale generated plugin artifact/);
  }, 30_000);

  test("rejects an extra generated chunk", async () => {
    const built = await artifacts();
    const dist = materialize(built);
    const extra = resolve(dist, "stale-extra.js");
    mkdirSync(dirname(extra), { recursive: true });
    writeFileSync(extra, "extra");

    expect(() => assertPluginRuntimeArtifactsExact(dist, built)).toThrow(/artifact set/);
  }, 30_000);
});
