import { afterEach, describe, expect, test } from "bun:test";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import {
  PLUGIN_BUILD_BUN_VERSION,
  assertPluginBuildBunVersion,
  assertPluginRuntimeArtifactsExact,
  portablePluginRuntimeArtifacts,
} from "../scripts/build-plugin-runtime";

const repoRoot = resolve(import.meta.dir, "..");
const generatorEntrypoint = resolve(repoRoot, "scripts/build-plugin-runtime.ts");
const committedDist = resolve(repoRoot, "plugins/claude-code/dist");
const pluginRuntimeArtifactPaths = [
  "semctx-index-worker.js",
  "semctx-mcp.js",
  "semctx-shared.js",
  "semctx.js",
] as const;
const pluginRuntimeCoreArtifactPaths = ["semctx-mcp.js", "semctx-shared.js", "semctx.js"] as const;
const portableTypeScriptPrelude =
  'var __dirname=import.meta.dir+"/typescript-lib",__filename=__dirname+"/typescript.js";';
const temporary: string[] = [];
let builtArtifacts: Promise<Map<string, Uint8Array>> | undefined;

/**
 * Keep the split runtime build isolated from the `bun test` process: a failed in-process build can
 * poison the runner's module resolver for the remaining files. The generator is therefore never
 * called here: a child process runs the real entrypoint in `--check` mode, which
 * builds the expected artifacts in memory and asserts the committed bytes of both plugin dists equal
 * that build. Once it succeeds, the committed bytes *are* the generated bytes, so this test reads
 * them off disk.
 */
async function verifiedArtifacts(): Promise<Map<string, Uint8Array>> {
  const child = Bun.spawn([process.execPath, generatorEntrypoint, "--check"], {
    cwd: repoRoot,
    stdin: "ignore",
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
    child.exited,
  ]);
  if (exitCode !== 0) {
    throw new Error(
      `plugin artifact check subprocess exited with code ${exitCode}\nstdout:\n${stdout}\nstderr:\n${stderr}`,
    );
  }

  const built = new Map<string, Uint8Array>();
  for (const artifactPath of pluginRuntimeArtifactPaths) {
    built.set(artifactPath, new Uint8Array(readFileSync(resolve(committedDist, artifactPath))));
  }
  return built;
}

function artifacts(): Promise<Map<string, Uint8Array>> {
  builtArtifacts ??= verifiedArtifacts();
  return builtArtifacts;
}

function chunkPath(paths: string[]): string {
  const chunks = paths.filter((path) => path === "semctx-shared.js");
  expect(chunks).toHaveLength(1);
  return chunks[0]!;
}

function materialize(built: Map<string, Uint8Array>): string {
  const dist = mkdtempSync(join(tmpdir(), "semctx-plugin-artifacts-"));
  temporary.push(dist);
  for (const [relativePath, bytes] of built) {
    const output = resolve(dist, relativePath);
    mkdirSync(dirname(output), { recursive: true });
    writeFileSync(output, bytes);
  }
  return dist;
}

afterEach(() => {
  for (const path of temporary.splice(0)) {
    rmSync(path, { recursive: true, force: true });
  }
});

describe("split plugin runtime build", () => {
  test("emits both public entries and one shared chunk", async () => {
    const built = await artifacts();
    const paths = [...built.keys()].sort();

    expect(paths).toContain("semctx-mcp.js");
    expect(paths).toContain("semctx.js");
    expect(paths).toContain("semctx-index-worker.js");
    expect(paths).toHaveLength(4);
    chunkPath(paths);
  }, 30_000);

  test("places portable TypeScript payloads only in the shared runtime and standalone worker", async () => {
    const built = await artifacts();
    const paths = [...built.keys()];
    const sharedChunk = chunkPath(paths);

    for (const [relativePath, bytes] of built) {
      const body = new TextDecoder().decode(bytes);
      expect(body).not.toContain(JSON.stringify(repoRoot).slice(1, -1));
      expect(body).not.toMatch(/typescript@[^"']+node_modules[^"']+typescript[^"']+lib/);
      expect(body.includes(portableTypeScriptPrelude)).toBe(
        relativePath === sharedChunk || relativePath === "semctx-index-worker.js",
      );
    }
  }, 30_000);

  test("diagnoses an unsupported Bun generator version", () => {
    expect(Bun.version).toBe(PLUGIN_BUILD_BUN_VERSION);
    expect(() => assertPluginBuildBunVersion("0.0.0-test")).toThrow(
      new RegExp(`requires Bun ${PLUGIN_BUILD_BUN_VERSION}`),
    );
  });
});

/**
 * `Bun.build` cannot run inside `bun test`, so the suite above can only observe that today's Bun
 * happens to place the prelude in the shared chunk. These cases drive the generator's own topology
 * gate with forged split output — the only way to prove it *refuses* a misplaced prelude instead of
 * counting one and moving on. Preludes are injected rather than imported so the fixtures stay
 * independent of the generator's checkout-bound strings.
 */
describe("shared TypeScript prelude topology", () => {
  const prelude = {
    bundled: 'var __dirname="/forged/checkout/node_modules/typescript/lib";',
    portable: 'var __dirname=import.meta.dir+"/typescript-lib";',
  };

  function generatedSources(preludeByPath: Record<string, string> = {}): Map<string, string> {
    return new Map(
      pluginRuntimeCoreArtifactPaths.map((path): [string, string] => [
        path,
        `// ${path}\n${preludeByPath[path] ?? ""}\n`,
      ]),
    );
  }

  test("accepts the prelude when only the shared chunk carries it", () => {
    const built = portablePluginRuntimeArtifacts(
      generatedSources({ "semctx-shared.js": prelude.bundled }),
      prelude,
    );

    expect([...built.keys()].sort()).toEqual([...pluginRuntimeCoreArtifactPaths].sort());
    for (const [path, bytes] of built) {
      const body = new TextDecoder().decode(bytes);
      expect(body).not.toContain(prelude.bundled);
      expect(body.includes(prelude.portable)).toBe(path === "semctx-shared.js");
    }
  });

  test("rejects a single prelude hoisted into an entry bundle", () => {
    expect(() =>
      portablePluginRuntimeArtifacts(
        generatedSources({ "semctx-mcp.js": prelude.bundled }),
        prelude,
      )
    ).toThrow(
      /exactly one bundled TypeScript path prelude, in semctx-shared\.js/,
    );
  });

  test("rejects a prelude duplicated across the shared chunk and an entry bundle", () => {
    expect(() =>
      portablePluginRuntimeArtifacts(
        generatedSources({ "semctx-shared.js": prelude.bundled, "semctx.js": prelude.bundled }),
        prelude,
      )
    ).toThrow(/bundled TypeScript path prelude/);
  });

  test("rejects a build that emits no prelude at all", () => {
    expect(() => portablePluginRuntimeArtifacts(generatedSources(), prelude)).toThrow(
      /bundled TypeScript path prelude/,
    );
  });

  test("rejects an entry bundle that already ships the portable prelude", () => {
    // Bundled stage passes (one absolute prelude, in the shared chunk); only the post-rewrite
    // check can see that an entry still carries a portable TypeScript path of its own.
    expect(() =>
      portablePluginRuntimeArtifacts(
        generatedSources({
          "semctx-shared.js": prelude.bundled,
          "semctx-mcp.js": prelude.portable,
        }),
        prelude,
      )
    ).toThrow(
      /exactly one portable TypeScript path prelude, in semctx-shared\.js/,
    );
  });

  test("rejects an artifact set that is not exactly the public runtimes and worker", () => {
    const sources = generatedSources({ "semctx-shared.js": prelude.bundled });
    sources.set("semctx-extra.js", "// extra\n");

    expect(() => portablePluginRuntimeArtifacts(sources, prelude)).toThrow(
      /unexpected split plugin artifact set/,
    );
  });

  // The gate is only load-bearing if the generator routes its Bun output through it, and no test
  // can observe that at runtime while `Bun.build` is unusable here.
  test("the generator routes its split build output through the topology gate", () => {
    const source = readFileSync(generatorEntrypoint, "utf8");

    expect(source).toContain("portablePluginRuntimeArtifacts(generated)");
  });
});

describe("exact plugin runtime artifact set", () => {
  test("accepts the complete generated set", async () => {
    const built = await artifacts();
    const dist = materialize(built);

    expect(() => assertPluginRuntimeArtifactsExact(dist, built)).not.toThrow();
  }, 30_000);

  test("rejects a missing shared chunk", async () => {
    const built = await artifacts();
    const dist = materialize(built);
    const sharedChunk = chunkPath([...built.keys()]);
    rmSync(resolve(dist, sharedChunk));

    expect(() => assertPluginRuntimeArtifactsExact(dist, built)).toThrow(/artifact set/);
  }, 30_000);

  test("rejects stale shared chunk bytes", async () => {
    const built = await artifacts();
    const dist = materialize(built);
    const sharedChunk = chunkPath([...built.keys()]);
    writeFileSync(resolve(dist, sharedChunk), "stale");

    expect(() => assertPluginRuntimeArtifactsExact(dist, built)).toThrow(/stale generated plugin artifact/);
  }, 30_000);

  test("rejects an extra generated chunk", async () => {
    const built = await artifacts();
    const dist = materialize(built);
    const extra = resolve(dist, "stale-extra.js");
    mkdirSync(dirname(extra), { recursive: true });
    writeFileSync(extra, "extra");

    expect(() => assertPluginRuntimeArtifactsExact(dist, built)).toThrow(/artifact set/);
  }, 30_000);
});
