// Generated by bun scripts/analyzer-identity.ts; do not edit.
// Covers 285 implementation/configuration files and TypeScript 5.9.3.
export const QUALIFIED_ANALYZER_IDENTITY = "sha256:fbc3037f5eead146d033f07bf338537e229d096203c28651127bb5e5233a9879";
