// Generated by bun scripts/analyzer-identity.ts; do not edit.
// Covers 280 implementation/configuration files and TypeScript 5.9.3.
export const QUALIFIED_ANALYZER_IDENTITY = "sha256:6f9c3a923d72248fa4ab64e613076557d42b75bb3255806d0085b98190d8444f";
