// Generated by bun scripts/analyzer-identity.ts; do not edit.
// Covers 280 implementation/configuration files and TypeScript 5.9.3.
export const QUALIFIED_ANALYZER_IDENTITY = "sha256:a32028edece0074e6b67bd1e1ef146db3aefbfd1b909ed5856596d0a6bd2c00d";
