// Generated by bun scripts/analyzer-identity.ts; do not edit.
// Covers 280 implementation/configuration files and TypeScript 5.9.3.
export const QUALIFIED_ANALYZER_IDENTITY = "sha256:59759746c53bfaae941e64295a55c72a8c112dc506ca4443666c1df4cb161c91";
