// Generated by bun scripts/analyzer-identity.ts; do not edit.
// Covers 280 implementation/configuration files and TypeScript 5.9.3.
export const QUALIFIED_ANALYZER_IDENTITY = "sha256:5821b61d369995df0e6b20ac9bce47928d8893fc325313f76651f0e6fd544de9";
