// Generated by bun scripts/analyzer-identity.ts; do not edit.
// Covers 286 implementation/configuration files and TypeScript 5.9.3.
export const QUALIFIED_ANALYZER_IDENTITY = "sha256:a24a9ed9697507b15b42ca84e29a6e71181f99276adae6b402acfb7bfe8b68d2";
