import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import ts from "typescript";

const GENERATED = "packages/app-services/src/analyzer-identity-generated.ts";
const hash = (bytes: string | Uint8Array): string => `sha256:${createHash("sha256").update(bytes).digest("hex")}`;

function sources(root: string, directory: string): string[] {
  return readdirSync(join(root, directory), { withFileTypes: true }).flatMap((entry) => {
    const path = `${directory}/${entry.name}`;
    if (entry.isDirectory()) return sources(root, path);
    if (!entry.isFile() || !/\.(?:ts|js|mjs)$/.test(entry.name) || path === GENERATED) return [];
    return [path];
  });
}

/** Exact implementation bytes, pinned dependencies and compiler, independent of checkout path. */
export function analyzerIdentity(root: string): { schemaVersion: 1; digest: string; files: { path: string; digest: string }[]; compiler: { version: string; digest: string } } {
  const paths = ["bun.lock", "tsconfig.json", "tsconfig.base.json", "scripts/analyzer-identity.ts", "scripts/build-plugin-runtime.ts", "scripts/build-cli-package.ts"];
  for (const entry of readdirSync(join(root, "packages"), { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    paths.push(`packages/${entry.name}/package.json`, ...sources(root, `packages/${entry.name}/src`));
  }
  paths.push("apps/cli/package.json", ...sources(root, "apps/cli/src"));
  const files = [...new Set(paths)].sort().map((path) => ({ path, digest: hash(readFileSync(join(root, path))) }));
  const compilerEntry = Bun.resolveSync("typescript", root);
  const compilerLibrary = dirname(compilerEntry);
  const compilerFiles = ["../package.json", ...readdirSync(compilerLibrary).filter((name) => /^lib.*\.d\.ts$/.test(name))].sort();
  const compiler = { version: ts.version, digest: hash(JSON.stringify({
    entry: hash(readFileSync(compilerEntry)),
    libraries: compilerFiles.map((path) => ({ path, digest: hash(readFileSync(join(compilerLibrary, path))) })),
  })) };
  const manifest = { schemaVersion: 1 as const, files, compiler };
  return { ...manifest, digest: hash(JSON.stringify(manifest)) };
}

export function generatedAnalyzerIdentity(root: string): string {
  const identity = analyzerIdentity(root);
  return `// Generated by bun scripts/analyzer-identity.ts; do not edit.\n// Covers ${identity.files.length} implementation/configuration files and TypeScript ${identity.compiler.version}.\nexport const QUALIFIED_ANALYZER_IDENTITY = ${JSON.stringify(identity.digest)};\n`;
}

if (import.meta.main) {
  const root = resolve(dirname(import.meta.path), "..");
  const path = join(root, GENERATED);
  const expected = generatedAnalyzerIdentity(root);
  if (process.argv.includes("--check")) {
    if (readFileSync(path, "utf8") !== expected) throw new Error("Analyzer implementation identity is stale; run bun scripts/analyzer-identity.ts before building.");
  } else {
    writeFileSync(path, expected);
  }
  console.log(JSON.stringify({ kind: "analyzer_identity", ...analyzerIdentity(root), generated: relative(root, path).replaceAll("\\", "/") }));
}
