import type { ContextPack, Claim, RecommendedRead } from "@semantic-context/core";
import { c, info, heading } from "./output";

function claimLine(claim: Claim): string {
  return `- (${claim.kind}/${claim.verificationStatus}, authority ${claim.authority.toFixed(2)}) ${claim.statement}`;
}

function readLine(read: RecommendedRead): string {
  return `- [${read.priority}] ${read.path}\n    why: ${read.reason}\n    evidence: ${read.evidenceIds.join(", ") || "(none)"}`;
}

/** Full markdown rendering, persisted next to the JSON pack. */
export function renderPackMarkdown(pack: ContextPack): string {
  const t = pack.taskFrame;
  const lines: string[] = [];
  lines.push(`# Context Pack — ${t.id}`);
  lines.push("");
  lines.push(`> Generated by ${pack.meta.generator} at ${pack.generatedAt}`);
  lines.push(`> Question kind: **${pack.meta.questionKind}** · deterministic: ${pack.meta.deterministic} · providers: [${pack.meta.candidateProviders.join(", ")}]`);
  lines.push("");
  lines.push(`## Task`);
  lines.push(`- mode: **${t.mode}**`);
  lines.push(`- rawTask: ${t.rawTask.split(/\r?\n/)[0] ?? ""}`);
  if (t.capabilities.length > 0) lines.push(`- capabilities: ${t.capabilities.join(", ")}`);
  if (t.boundedContexts.length > 0) lines.push(`- bounded contexts: ${t.boundedContexts.join(", ")}`);
  if (t.hardInvariants.length > 0) lines.push(`- invariants: ${t.hardInvariants.join(", ")}`);
  lines.push("");

  lines.push(`## Hard constraints (non-negotiable)`);
  lines.push(pack.hardConstraints.length > 0 ? pack.hardConstraints.map(claimLine).join("\n") : "_none identified_");
  lines.push("");

  lines.push(`## Authoritative claims`);
  lines.push(pack.authoritativeClaims.length > 0 ? pack.authoritativeClaims.map(claimLine).join("\n") : "_none_");
  lines.push("");

  lines.push(`## Recommended reads`);
  lines.push(pack.recommendedReads.length > 0 ? pack.recommendedReads.map(readLine).join("\n") : "_none_");
  lines.push("");

  lines.push(`## Impact paths`);
  lines.push(
    pack.impactPaths.length > 0 ? pack.impactPaths.map((p) => `- ${p.description}`).join("\n") : "_no call paths found_",
  );
  lines.push("");

  lines.push(`## Relevant tests`);
  lines.push(
    pack.relevantTests.length > 0 ? pack.relevantTests.map((tn) => `- ${tn.filePath ?? tn.name}`).join("\n") : "_none_",
  );
  lines.push("");

  lines.push(`## Contradictions (NON-normative — do not treat as truth)`);
  lines.push(
    pack.contradictions.length > 0 ? pack.contradictions.map(claimLine).join("\n") : "_none detected_",
  );
  lines.push("");

  lines.push(`## Unknowns`);
  lines.push(pack.unknowns.length > 0 ? pack.unknowns.map((u) => `- ${u}`).join("\n") : "_none_");
  lines.push("");

  lines.push(`## Verification plan`);
  for (const step of pack.verificationPlan.steps) {
    lines.push(`- (${step.kind}) ${step.description}${step.command ? `  \`${step.command}\`` : ""}`);
  }
  if (pack.verificationPlan.requiredTests.length > 0) {
    lines.push(`- required tests: ${pack.verificationPlan.requiredTests.join(", ")}`);
  }
  lines.push("");

  return `${lines.join("\n")}\n`;
}

/** Concise console rendering. */
export function renderPackConsole(pack: ContextPack): void {
  const t = pack.taskFrame;
  heading(`Context Pack for ${t.id}  (${pack.meta.questionKind}, mode=${t.mode})`);

  heading("Hard constraints");
  if (pack.hardConstraints.length === 0) info(c.dim("  none"));
  for (const claim of pack.hardConstraints) info(`  ${c.red("!")} ${claim.statement} ${c.dim(`[${claim.verificationStatus}]`)}`);

  heading("Recommended reads (justified)");
  for (const read of pack.recommendedReads) {
    const tag = read.priority === "critical" ? c.red(read.priority) : read.priority === "high" ? c.yellow(read.priority) : c.dim(read.priority);
    info(`  ${tag}  ${c.cyan(read.path)}`);
    info(`      ${c.dim(read.reason)}`);
  }
  if (pack.recommendedReads.length === 0) info(c.dim("  none"));

  heading("Impact paths");
  for (const path of pack.impactPaths) info(`  ${path.description}`);
  if (pack.impactPaths.length === 0) info(c.dim("  none"));

  heading("Relevant tests");
  for (const test of pack.relevantTests) info(`  ${c.green(test.filePath ?? test.name)}`);
  if (pack.relevantTests.length === 0) info(c.dim("  none"));

  heading("Contradictions (non-normative)");
  for (const claim of pack.contradictions) info(`  ${c.yellow("~")} ${claim.statement} ${c.dim(`[${claim.verificationStatus}]`)}`);
  if (pack.contradictions.length === 0) info(c.dim("  none"));

  heading("Unknowns");
  for (const unknown of pack.unknowns) info(`  ${c.dim("?")} ${unknown}`);
  if (pack.unknowns.length === 0) info(c.dim("  none"));

  heading("Verification plan");
  for (const step of pack.verificationPlan.steps) {
    info(`  ${c.blue(step.kind)}: ${step.description}${step.command ? c.dim(`  (${step.command})`) : ""}`);
  }
}
